Es1.1
EdoardoGGEZ/esercizi pull request #1
Opened 2023-06-20 09:52 UTC by EdoardoGGEZ

media di n numeri

2023-06-21 15:31 UTC, giannivalenti requested changes
I would suggest some changes:
- please format the code using an automatic formatter (with VSCode you can format the opened document with `Shift` + `Alt` + `F`),
- please avoid declaring multiple variable on a single line (in general, in C++ you should try to declare them just before you use them),
- please fix the typos in variable names (`lengh` => `length`, etc.) and alwasy use english in your code (`media` => `mean`),
- please put each comment in a separate line, ideally just before the code line it refers to.

2023-06-23 08:51 UTC, giannivalenti approved these changes

2023-06-23 09:49 UTC, giannivalenti commented
@lucaotta , per me questa PR va bene. A te la parola.

2023-06-27 08:15 UTC, lucaotta approved these changes
Ok anche per me. Passiamo avanti!

2023-06-27 10:07 UTC, merged