Clock2_2
EdoardoGGEZ/esercizi pull request #13
Opened 2023-07-17 10:27 UTC by EdoardoGGEZ

2023-07-17 11:52 UTC, lucaotta requested changes
Mi sembra buono, ho solo due piccole richieste per terminare la PR

2023-07-17 11:52 UTC, lucaotta commented on clock/PageAlarmList.qml
> +        text: "Alarm clock list"
[nitpick] Ecco, questo potrebbe essere un buon candidato per `qsTr()`

2023-07-17 11:52 UTC, lucaotta commented on clock/PageAlarmList.qml
> +        anchors {
Ti manca un `clip:true`. Prova a trascinare su/giù la lista per vedere l'effetto che fa :)

2023-07-18 10:10 UTC, giannivalenti approved these changes

2023-07-18 15:09 UTC, merged