add exercise 1.2
EdoardoGGEZ/esercizi pull request #3
Opened 2023-06-21 14:38 UTC by EdoardoGGEZ

es1.2

2023-06-21 16:14 UTC, giannivalenti requested changes
I would suggest some changes:
- please format the code using an automatic formatter (with VSCode you can format the opened document with `Shift` + `Alt` + `F`),
- please fix the typos in variable names (`lengh` => `length`, etc.) and alwasy use english for variable names in your code &mdash; this doesn't apply to user messages.

2023-06-21 16:14 UTC, giannivalenti commented on cpp/es1.2/medianaEdoardo.cpp
> +vector<double> bubleSort(vector<double> n){//algoritmo di sorting
- You should avoid copying the whole vector like this: in this case you should pass the argument by reference and modify it, i.e., the new signature could be `void bubbleSort(vector<double>& v)`.
- The variable name `n` is a bad choice for a vector. Can you find a better name (e.g, `vec`, `v`, `numbers`...)?

2023-06-21 16:14 UTC, giannivalenti commented on cpp/es1.2/medianaEdoardo.cpp
> +                int app=n.at(i);
You could try using `swap(n[i], n[i + 1])` (see `std::swap` reference [here](https://cplusplus.com/reference/algorithm/swap/)).

2023-06-21 16:14 UTC, giannivalenti commented on cpp/es1.2/medianaEdoardo.cpp
> +            if(n.at(i)>n.at(i+1)){//se il vector non è in ordine
You can replace `at()` with square-bracket operator here (i.e., `vec[i]`) to avoid bound checking at each call.

2023-06-22 07:27 UTC, lucaotta requested changes

2023-06-22 07:27 UTC, lucaotta commented on cpp/es1.2/medianaEdoardo.cpp
> +        esci=true;//condizione di uscita
Sposterei anche i commenti alla riga precedente. I commenti inline (= nella stessa riga) di solito vanno evitati per questioni di leggibilità

2023-06-23 10:02 UTC, giannivalenti requested changes
Ottimo lavoro, hai recepito tutte le richieste che ti abbiamo fatto ed applicato le modifiche.

Ti chiederei le ultime due modifiche (cioè altri due commit ben separati):
- Imposta VSCode in modo che i file vengano automaticamente formattati ogni volta che li salvi (`Ctrl` + `Shift` + `P` => `Preferences: Open User Settings` => `Format On Save`) ed aggiungi un commit separato dove salvi il file e cambia _solo_ la formattazione.
- Di solito quando possibile si evita di scrivere un `do`-`while` perché è un po' meno comprensibile rispetto ad un semplice `while`. Riusciresti a riscrivere il loop nella funzione `bubbleSort()` in una forma come questa?
  ```C++
  bool exit_condition = false;
  while (!exit_condition)
  {
      exit_condition = true;
      // ...
  }
  ```
  Nel codice di esempio ti suggerisco anche di dare un nome il più esplicito possibile alle variabili. Lo scopo è sempre quello di rendere il codice che scrivi immediatamente comprensibile, per quanto possibile, a chi lo legge.

2023-06-23 10:53 UTC, lucaotta approved these changes
Risolti gli ultimi commenti di Gianni per me è ok

2023-06-27 14:49 UTC, merged