add exercise 1.3
EdoardoGGEZ/esercizi pull request #4
Opened 2023-06-21 14:43 UTC by EdoardoGGEZ

es1.3

2023-06-22 07:40 UTC, lucaotta requested changes
Ricordati anche di sistemare la formattazione del codice

2023-06-22 07:40 UTC, lucaotta commented on cpp/es1.3/modaEdoardo.cpp
> +    freopen("canto1.txt","r",stdin);//input da file
Qui stai mappando il file canto1 su stdin per poter usare cin per leggere, giusto?
Puoi anche aprire il file direttamente creando un `ifstream` e leggendo come se fosse `cin`.
Es.
```c++
std::ifstream input("canto1.txt", "r");
string str;
input >> str;
```

2023-06-22 07:40 UTC, lucaotta commented on cpp/es1.3/modaEdoardo.cpp
> +    // Suggerimento: usare `std::map` o `std::unordered_map`
Uhm, questo commento direi di toglierlo e provare ad usare `std::map` al posto di due vettori paralleli.
`std::map` è una mappa chiave-valore: prova a riorganizzare il codice, vedrai che viene più semplice

2023-06-22 07:40 UTC, lucaotta commented on cpp/es1.3/modaEdoardo.cpp
> +        string app=parole.at(i);
Posso suggerire un nome diverso tipo `parola` o `word`? Non capisco che abbreviazione sia `app`

2023-06-23 09:36 UTC, EdoardoGGEZ commented on cpp/es1.3/modaEdoardo.cpp
> +        string app=parole.at(i);
app sta per appoggio

2023-06-23 14:08 UTC, giannivalenti commented on cpp/es1.3/modaEdoardo.cpp
> +    freopen("canto1.txt","r",stdin);//input da file
Se accetti il consiglio di Luca, puoi controllare se sei alla fine del file così:
```C++
while (!input.eof())
{
    input >> str;
    // ....
}
```

2023-06-27 08:13 UTC, lucaotta approved these changes
Ok, direi che per me è a posto. Ottimo lavoro!

2023-06-27 14:49 UTC, merged