esercizio es1_1
EdoardoGGEZ/esercizi pull request #6
Opened 2023-07-03 10:08 UTC by EdoardoGGEZ

2023-07-03 10:15 UTC, giannivalenti requested changes

2023-07-03 10:15 UTC, giannivalenti commented on qml/es1_1/es1_1/SwitchButton.qml
> +    anchors.centerIn: parent
Possiamo rimuovere questa linea, così la posizione di questo elemento la decide solo il `Main` che lo istanzia.

2023-07-03 10:15 UTC, giannivalenti commented on qml/es1_1/es1_1/SwitchButton.qml
> +        onClicked: parent.state = "on"
Puoi provare a moficare questa funzione in modo che se lo stao è "on" lo cambia a "off" e viceversa? Così non c'è bisogno di aggiungere il `PropertyChange` che modifica `onClicked`.

2023-07-04 11:14 UTC, lucaotta approved these changes

2023-07-04 11:49 UTC, giannivalenti approved these changes

2023-07-04 11:49 UTC, merged