Qml/es1 3
EdoardoGGEZ/esercizi pull request #8
Opened 2023-07-04 09:49 UTC by EdoardoGGEZ

2023-07-04 14:52 UTC, lucaotta commented
Insieme all'esercizio 1_3 c'è anche l'esercizio 1_1. Riesci a separare le due cose @EdoardoGGEZ ?

2023-07-04 15:00 UTC, EdoardoGGEZ commented
> Insieme all'esercizio 1_3 c'è anche l'esercizio 1_1. Riesci a separare le due cose @EdoardoGGEZ ?

non credo di esserne in grado @lucaotta

2023-07-04 15:54 UTC, lucaotta requested changes
Dividerei in due la PR, hai due esercizi in uno

2023-07-04 15:54 UTC, lucaotta commented on qml/es1_3/es1_3/Main.qml
> +            signal close
Non mi è chiaro a cosa ti serva definire questi segnali, non mi  sembra che vengano utilizzati mai da nessuna parte

2023-07-04 15:54 UTC, lucaotta commented on qml/es1_3/es1_3/Chapter.qml
> +                    parent.state = "default"
Mi aspettavo di vedere impostati  `content.state`, non il parent. Quando fai gli assegnamenti ti suggerisco di usare un  id specifico piuttosto che parent. Così anche se sposti questo pezzo di Javascript altrove nel componente ti continua a funzionare

2023-07-04 15:54 UTC, lucaotta commented on qml/es1_3/es1_3/Chapter.qml
> +            horizontalAlignment: Text.AlignHCenter
Il testo si calcola di già le sue dimensioni, puoi evitare di specificarle e ancorare l'elemento testo con le ancore. Le dimensioni esplicite ti servono per mandare a capo il testo se è troppo lungo

2023-07-06 10:15 UTC, giannivalenti approved these changes

2023-07-06 10:15 UTC, giannivalenti commented
@lucaotta, anche questa per me va bene.

2023-07-06 14:53 UTC, lucaotta approved these changes
Va bene anche per me

2023-07-06 14:53 UTC, lucaotta commented
@EdoardoGGEZ a te l'onore di fare il merge

2023-07-07 09:58 UTC, merged